covidbelgium/routes.py
from flask import render_template, send_from_directory, request, redirect, Response, abort, Blueprint, g, url_for, session, current_app
from flask_babel import gettext

from covidbelgium import get_locale
from covidbelgium.database import db_session
from covidbelgium.ip_check import IPBan
from covidbelgium.models import Answers, Sex, LikelyScale
from datetime import date, datetime, timedelta

from covidbelgium.passwords import gen_password, hash_password, check_password

multilingual = Blueprint('multilingual', __name__, template_folder='templates', url_prefix='/<lang>')
main_form_ip_check = IPBan(limit=10, add_day_to_key=True)

@multilingual.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang', g.locale)


@multilingual.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.locale = values.pop('lang')


@multilingual.before_request
def before_request():
    get_locale()
    if g.locale not in ["fr", "en", "nl", "de"]:
        abort(404)


def get_password_list():
    """ List previously-used passwords from the cookie """
    return session.get('passwords', [])


def add_password_to_list(password: str):
    """ Takes a response object, and update the cookie for the password with the new password. """
    pwds = get_password_list()
    if password not in pwds:
        pwds = [password] + pwds
    session["passwords"] = pwds


def parse_date(string):
    """ Parses a date, in multiple possible formats %d/%m/%Y and %Y-%m-%d. """
    try:
        return datetime.strptime(string, '%d/%m/%Y').date()
    except:
        return datetime.strptime(string, '%Y-%m-%d').date()


@multilingual.route('/')
@multilingual.route('/index')
def index(error=False):
    passwords = get_password_list()
    passwords = passwords[:15]  # max 15 profiles listed.
    entries = {pwd: Answers.find_last_by_hash(hash_password(pwd)) for pwd in passwords}
    entries = {pwd: entry for pwd, entry in entries.items() if entry is not None}
    return render_template('index.html', entries=entries, ip_ok=main_form_ip_check.is_ok())


@multilingual.route('/index-error')
def index_error():
    return index(True)


@multilingual.route("/new-id")
def new_id():
    locale = str(get_locale())
    session["cur_pass"] = gen_password(locale)
    resp = redirect(url_for('multilingual.form'), 302)
    return resp


@multilingual.route("/reuse-id", methods=["GET", "POST"])
def reuse_id():
    password = request.form.get("password", "")
    if check_password(password) and Answers.find_last_by_hash(hash_password(password)) is not None:
        add_password_to_list(password)
        session["cur_pass"] = password
        return redirect(url_for('multilingual.form'), 302)
    else:
        return render_template('reuse-id.html', password=password)


@multilingual.route("/form", methods=["GET", "POST"])
def form():
    password = session.get("cur_pass")
    if password is None or not main_form_ip_check.is_ok():
        return redirect(url_for('multilingual.index_error'), 302)

    last_answer = Answers.find_last_by_hash(hash_password(password))

    if request.method == "GET":  # Serve the form
        session["form_opened"] = datetime.utcnow()

        if last_answer is not None:
            return render_template('form.html', password=password, current={
                "sex": last_answer.sex.name,
                "age": last_answer.age,
                "covid_likely": last_answer.covid_likely.name,
                "covid_start": last_answer.covid_since,
                "covid_end": last_answer.covid_until,
                "municipality": last_answer.municipality,
                "symptoms": last_answer.get_active_symptoms_dict()
            }, all_symptoms=Answers.all_symptoms, existing=True)
        else:
            return render_template('form.html',
                                   password=password,
                                   all_symptoms=Answers.all_symptoms,
                                   current={},
                                   existing=False)
    else:  # Save in db and serve next form

        # "session expired"
        if session.get("form_opened") is not None and datetime.utcnow() - session.get("form_opened") > timedelta(hours=1):
            return redirect(url_for('multilingual.index_error'), 302)

        errors = []

        def check_form(f, error_msg, additional_check=lambda x: True):
            try:
                v = f()
                if not additional_check(v):
                    raise Exception()
                return v
            except:
                errors.append(error_msg)
                return None

        sex = check_form(lambda: Sex[request.values['sex']], gettext("Please fill in your sex"))
        age = check_form(lambda: int(request.values['age']), gettext("Please fill in your age"), lambda x: x % 5 == 0 and x <= 120)
        municipality = check_form(lambda: int(request.values['municipality']), gettext("Please fill in your municipality"))

        symptoms = {x: request.values.get(f'symptoms_{x}') is not None for x in Answers.all_symptoms.keys()}

        covid_likely = check_form(lambda: LikelyScale[request.values['status']], gettext("Please select your status w.r.t Covid-19."))
        if covid_likely != LikelyScale.extremely_unlikely:
            covid_start = check_form(lambda: parse_date(request.values.get("timing_from")), gettext("Invalid date format. Please enter it as dd/mm/yyyy, like 20/03/2019."))
            covid_end = check_form(lambda: parse_date(request.values.get("timing_to")), gettext("Invalid date format. Please enter it as dd/mm/yyyy, like 20/03/2019."))

            if covid_start is not None and covid_end is not None and covid_start > covid_end:
                errors.append(gettext('Invalid dates, you should fall ill before being cared.'))
            if covid_start is not None and (covid_start < date(2019, 12, 1) or covid_start > date.today()):
                errors.append(gettext('Invalid start of symptoms date.'))
            if not any(symptoms.values()):
                errors.append(gettext('If you think you are/were ill, please select the symptoms you faced. If you did not experience any of them, it is extremely unlikely you had covid-19.'))
        else:
            covid_start = covid_end = None
            if any(symptoms.values()):
                errors.append(gettext("If you had some symptoms, it is not extremely unlikely that you had Covid-19."))

        if len(errors) == 0:
            if covid_end is not None and covid_end > date.today():
                covid_end = date(2030, 1, 1)  # far in the future, but every entry has the same date.

            # now it's time to check if the remote person was not a robot. If this is the case, we silently ignore
            # its submission.
            is_robot = False
            if request.values.get('c-1', '') != '':
                current_app.logger.info('Robot filled the c-1 variable')
                is_robot = True
            if request.values.get('c-2', '') != password.split("-")[0]:
                current_app.logger.info('Robot filled the c-2 variable incorrectly')
                is_robot = True
            if session.get("form_opened") is None:
                current_app.logger.info('Robot did not load the form first, or someone already submitted the form')
                is_robot = True
            elif last_answer is None and datetime.utcnow() - session.get("form_opened") < timedelta(seconds=4):
                current_app.logger.info('Robot filled the form a bit too fast %s', str(datetime.utcnow() - session.get("form_opened")))
                is_robot = True

            if not is_robot:
                answer = Answers(hash_password(password), covid_likely, sex, age, municipality, covid_start, covid_end, symptoms)
                db_session.add(answer)
                db_session.commit()

            # You can submit only once :-)
            session["form_opened"] = None
            # Update the IP checker
            main_form_ip_check.incr()
            # This password is now valid
            add_password_to_list(password)

            return render_template('form_distancing.html', password=password)
        else:
            return render_template('form.html', password=password, errors=errors, current={
                "sex": (sex.name if sex is not None else None),
                "age": age,
                "symptoms": symptoms,
                "covid_likely": (covid_likely.name if covid_likely is not None else None),
                "covid_start": covid_start,
                "covid_end": covid_end,
                "municipality": municipality
            }, all_symptoms=Answers.all_symptoms, existing=last_answer is not None)


@multilingual.route("/social-distancing-form")
def social_distancing_form():
    password = session.get("cur_pass")
    if password is None:
        return redirect(url_for('multilingual.index_error'), 302)

    return render_template('form_distancing.html', password=password)

covidbelgium/templates/form.html
{% extends "tpl.html" %}
{% block content %}

    <p class="is-size-4 subtitle">
        {% if not existing %}
            {{ _("Fill this form to contribute.") }}
            {{ _('<a href="{}">Everything is strictly anonymous</a>, don\'t worry!').format("#") }}
        {% else %}
            {{ _("You are currently updating the profile <span class='is-family-code'>{}</span>. Thanks for helping us!").format(password) }}
        {% endif %}
    </p>

    <div id="error-message" class="notification is-danger {% if not errors %}is-hidden{% endif %}">
        {% for x in errors %}
            {{ x }}<br/>
        {% else %}
            {{ _("(no error... yet)") }}
        {% endfor %}
    </div>

    <form action="{{ url_for('multilingual.form') }}" method="post" name="main_form">
        <div class="field">
            <label for="sex" class="label">{{ _("Sex") }}</label>
            <div class="control">
                <div class="columns">
                    <div class="column">

                        <input class="is-checkradio is-block is-custom-checkradio-block" id="sex_male" type="radio"
                               name="sex" value="male" required {% if current.sex == "male" %}checked{% endif %}>
                        <label for="sex_male">{{ _("Male") }}</label>
                    </div>
                    <div class="column">
                        <input class="is-checkradio is-block is-custom-checkradio-block" id="sex_female" type="radio"
                               name="sex" value="female" required {% if current.sex == "female" %}checked{% endif %}>
                        <label for="sex_female">{{ _("Female") }}</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="field">
            <label for="age" class="label">{{ _("Age")}} </label>
            <div class="control">
                <div class="select is-primary">
                    <select name="age" id="age" required>
                        <option value="">{{ _("Select your age") }}</option>
                        {% for i in range(0, 125, 5) %}
                            <option value="{{ i }}" {% if current.age == i %}selected{% endif %}>{{ i }} - {{ i + 4 }} years</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="field">
            <label for="municipality" class="label">{{ _("Municipality code") }}</label>
            <input name="municipality" class="input is-primary" id="municipality" placeholder="1000" required
                   {% if current.municipality %}value="{{ current.municipality }}"{% endif %} >
        </div>
        <div class="field">
            <label for="status" class="label">{{ _("How likely is it that you suffer(ed) from COVID-19?") }}</label>
            {% set statuses = [('extremely_unlikely', _('Extremely unlikely')),
                                 ('unlikely', _("Unlikely (I had or still have very little symptoms)")),
                                 ('neutral', _("Maybe (I had or still have some symptoms)")),
                                 ('likely', _("Likely (I had or still have most symptoms)")),
                                 ('certain', _("Certain (confirmed by medical test)"))] %}
            <div class="control">
                <div class="columns">
                    {% for value, name in statuses %}
                        <div class="column">
                            <input class="is-checkradio is-block is-custom-checkradio-block"
                                   id="status_covid_{{ value }}" type="radio"
                                   name="status" value="{{ value }}" required
                                   {% if current.covid_likely == value%}checked{% endif %}
                            >
                            <label for="status_covid_{{ value }}">{{ name }}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div id="no-need-to-fill" class="notification is-primary is-hidden">
            {{ _("Good news, you don't need to fill the fields below, as you were/are not sick!") }} <br/>
            {{ _("Simply submit the form at the bottom of the page.") }}
        </div>
        <div class="field" id="when_sick_field">
            <label for="timing" class="label">{{ _("When were you sick?") }}</label>
            <div class="columns">
                <div class="column">
                    <label for="timing_covid" class="label">{{ _("From") }}</label>
                    <div class="control">
                        <input type="date" class="input is-primary" name="timing_from" id="timing_covid_from"
                               placeholder="{{ _("dd/mm/yyyy") }}"
                               {% if current.covid_start %} value="{{ current.covid_start }}"{% endif %}
                        />
                    </div>
                    <p class="help">{{ _("Put the date where your first symptom appeared") }}</p>
                </div>
                <div class="column">
                    <label for="timing_covid" class="label">{{ _("To") }}</label>
                    <div class="control">
                        <input type="date" class="input is-primary" name="timing_to" id="timing_covid_to"
                               placeholder="{{ _("dd/mm/yyyy") }}"
                               {% if current.covid_end %} value="{{ current.covid_end }}" {% endif %}
                        />
                    </div>
                    <p class="help">{{ _("If you are still ill, please put any date in the future") }}</p>
                </div>
            </div>
        </div>
        <div class="field" id="symptoms_field">
            <label for="symptoms" class="label">{{ _("Which symptoms did you experience?") }}</label>
            <div class="control">
                <div class="columns is-multiline is-mobile">
                    {% for value, name in all_symptoms.items() %}
                        <div class="column is-one-quarter-desktop is-one-third-tablet is-half-mobile">
                            <input class="is-checkradio is-block is-custom-checkradio-block"
                                   id="symptoms_{{ value }}" type="checkbox"
                                   name="symptoms_{{ value }}"
                                   {% if current.symptoms and current.symptoms[value] %}checked{% endif %}
                            >
                            <label for="symptoms_{{ value }}">{{ name }}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="field this-is-a-c-h-e-c-k">
            <label for="c-1" class="label">{{ _("Please do not fill this if you are a human") }}</label>
            <div class="control">
                <input class="input" id="c-1" type="text" name="c_1" placeholder="{{ _("do not fill me") }}">
            </div>
        </div>
        <noscript>
            <div class="field">
                <label for="c-2" class="label">{{ _("If you are not a droid, and purposefully deactivated javascript, fill this entry with the word '{}'").format(password.split("-")[0]) }}</label>
                <div class="control">
                    <input class="input" id="c-2" type="text" name="c_2" placeholder="{{ _("fill me with what's indicated above") }}">
                </div>
            </div>
        </noscript>
        <div class="field">
            <div class="buttons is-centered" style="margin-top: 3em">
                <button type="submit" class="button is-primary is-large">{{ _("Click here to continue") }}</button>
            </div>
        </div>

    </form>

    <script type="text/javascript">
        /* Disable the datetime fields + symptoms if "very unlikely" is selected */
        function disable_or_enable_field(field, new_status) {
            var inputs = field.getElementsByTagName('input');
            for(var i = 0; i < inputs.length; i++)
                inputs[i].disabled = !new_status;
            if (new_status) {
                field.classList.remove("is-disabled");
            }
            else {
                field.classList.add("is-disabled");
            }
        }

        function radio_status_checked(radio) {
            if(radio.value === "extremely_unlikely") {
                disable_or_enable_field(document.getElementById("when_sick_field"), false);
                disable_or_enable_field(document.getElementById("symptoms_field"), false);
                document.getElementById("no-need-to-fill").classList.remove("is-hidden");
            }
            else {
                disable_or_enable_field(document.getElementById("when_sick_field"), true);
                disable_or_enable_field(document.getElementById("symptoms_field"), true);
                document.getElementById("no-need-to-fill").classList.add("is-hidden");
            }
        }

        var rad = document.main_form.status;
        var prev = null;
        for (var i = 0; i < rad.length; i++) {
            rad[i].addEventListener('change', function() {
                if(this.checked)
                    radio_status_checked(this);
            });
            if(rad[i].checked)
                radio_status_checked(rad[i]);
        }

        /* Checks content before authorizing the form to be submitted */
        function get_date(date_str) {
            if(RegExp('[0-9]{4}-[0-9]{2}-[0-9]{2}').test(date_str)) {
                return new Date(date_str);
            }
            else if(RegExp('[0-9]{1,2}/[0-9]{1,2}/[0-9]{2,4}').test(date_str)) {
                var splitted = date_str.split("/");
                var day = splitted[0];
                if(day.length === 1)
                    day = "0"+day;
                var month = splitted[1];
                if(month.length === 1)
                    month = "0"+month;
                var year = splitted[2];
                if(year.length === 2)
                    year = "20"+year;
                return new Date(year+"-"+month+"-"+day);
            }
            return null;
        }

        function display_warning(message) {
            var error_box = document.getElementById("error-message");
            error_box.classList.remove("is-hidden");
            error_box.textContent = message;
            error_box.scrollIntoView();
        }

        function validateForm() {
            var status = document.main_form.status.value;
            if (status !== "extremely_unlikely") {
                var from = get_date(document.getElementById("timing_covid_from").value);
                var to = get_date(document.getElementById("timing_covid_to").value);

                if(from === null || to === null) {
                    display_warning("{{ _('Invalid date format. Please enter it as dd/mm/yyyy, like 20/03/2019.') }}");
                    return false;
                }

                if(from > to) {
                    display_warning("{{ _('Invalid dates, you should fall ill before being cared.') }}");
                    return false;
                }

                var symptoms_checkbox_names = [
                    {% for value in all_symptoms %}
                        "symptoms_{{ value }}",
                    {% endfor %}
                ];
                var count = 0;
                for(var i = 0; i < symptoms_checkbox_names.length; i++) {
                    if(document.getElementById(symptoms_checkbox_names[i]).checked)
                        count += 1;
                }

                if(count == 0) {
                    display_warning("{{ _('If you think you are/were ill, please select the symptoms you faced. If you did not experience any of them, it is extremely unlikely you had covid-19.') }}");
                    return false;
                }

                return true;
            }
        }

        // c-h-e-c-k
        var input = document.createElement("input");
        input.type = "hidden";
        input.name = "c-2";
        input.value = '{{ password.split("-")[0] }}';
        document.main_form.appendChild(input);
        document.main_form.onsubmit = validateForm;
    </script>
{% endblock %}

covidbelgium/templates/index.html
{% extends "tpl.html" %}
{% block abovecontent %}
     <section class="hero is-fullheight-with-navbar  is-primary is-bold">
        <div class="hero-body">
            <div class="container has-text-centered ">
                <h1 class="title is-size-1 ">
                    {{ _("Fight the virus with <span class='is-family-code'>data</span>!") }}
                </h1>
                {% if not ip_ok %}
                    <div class="notification is-danger">
                        {{ _("Your IP (aka people in your home) updated too many profiles today, please wait tomorrow. This ensures that we keep good quality data.") }}
                    </div>
                {% else %}
                    {% if entries %}
                        <h2 class="subtitle">{{ _("Select your profile to update it") }}</h2>
                        <div class="columns is-centered is-multiline">
                            {% for password, profile in entries.items() %}
                                <div class="column is-half-desktop is-half-tablet">
                                    <form action="{{ url_for('multilingual.reuse_id') }}" method="post">
                                        <input type="hidden" name="password" value="{{ password }}"/>
                                        <div class="box">
                                            <div class="is-size-4 is-family-code">{{ password }}</div>
                                            <div class="columns">
                                                <div class="column">
                                                    {% if profile.sex.value == 0 %}
                                                        {{_("Male")}}
                                                    {% else %}
                                                        {{_("Female")}}
                                                    {% endif %}
                                                </div>
                                                <div class="column">
                                                    {{ _("Age") }} {{ profile.age }} - {{ profile.age + 4 }}
                                                </div>
                                                <div class="column">
                                                    {% if profile.covid_likely.value == 1 %}
                                                        {{ _("Not ill") }}
                                                    {% else %}
                                                        {{ _("Is/was ill") }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <button type="submit" class="button is-primary">Update this profile</button>
                                        </div>
                                    </form>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="buttons is-centered">
                        {% if entries %}
                            <a href="{{ url_for('multilingual.new_id') }}" class="button is-dark is-centered">{{ _("I want to create another profile!") }}</a>
                        {% else %}
                            <a href="{{ url_for('multilingual.new_id') }}" class="button is-dark is-large is-centered">{{ _("I want to participate!") }}</a>
                        {% endif %}
                    </div>
                    <div class="buttons is-centered">
                        {% if entries %}
                            <a href="{{ url_for('multilingual.reuse_id') }}" class="button is-dark is-centered">{{ _("I already filled the form, but my profile is not listed above") }}</a>
                        {% else %}
                            <a href="{{ url_for('multilingual.reuse_id') }}" class="button is-dark is-centered">{{ _("I already filled the form, let me update it!") }}</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="hero-foot">
            <div class="container has-text-centered is-size-4">
                <p>⬇️ {{ _("More information below") }} ⬇️️</p>
            </div>
        </div>
    </section>
{% endblock %}
{% block content %}
    Test
{% endblock %}

covidbelgium/templates/reuse-id.html
{% extends "tpl.html" %}
{% block content %}
    <form action="{{ url_for('multilingual.reuse_id') }}" method="post">
        {% if password %}
            <p class="alert">Invalid password!</p>
        {% endif %}
        Please input your profile ID below to update your profile:

        <input name="password" value="{{ password }}"/>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

covidbelgium/templates/tpl.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Covid19-form</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bulma.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bulma-checkradio.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
        <script type="text/javascript" src="{{ url_for('static', filename='js/base.js') }}"></script>
    </head>
    <body>
        <nav class="navbar has-background-light" role="navigation" aria-label="main navigation">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item is-size-4" href="{{ url_for('multilingual.index') }}">
                        Covidata<span class="has-text-weight-bold">.uclouvain.be</span>
                    </a>

                    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                       data-target="navMenu">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>

                <div id="navMenu" class="navbar-menu">
                    <div class="navbar-end">
                        <div class="navbar-item">
                            <div class="buttons has-addons are-small">
                                {% if g.locale != "fr" %}
                                    <a class="button is-light"
                                       href="{{ url_for(request.endpoint, *dict(request.view_args), lang="fr") }}">FR</a>
                                {% endif %}
                                {% if g.locale != "nl" %}
                                    <a class="button is-light"
                                       href="{{ url_for(request.endpoint, *dict(request.view_args), lang="nl") }}">NL</a>
                                {% endif %}
                                {% if g.locale != "de" %}
                                    <a class="button is-light"
                                       href="{{ url_for(request.endpoint, *dict(request.view_args), lang="de") }}">DE</a>
                                {% endif %}
                                {% if g.locale != "en" %}
                                    <a class="button is-light"
                                       href="{{ url_for(request.endpoint, *dict(request.view_args), lang="en") }}">EN</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="navbar-item">
                            <div class="buttons">
                                <a class="button is-dark">Get the data</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        {% block abovecontent %}
        {% endblock %}
        <section class="section">
            <div class="container">
                {% block content %}
                    <div>main content</div>
                {% endblock %}
            </div>
        </section>
        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    {{ _('Covidata<span class="has-text-weight-bold">.uclouvain.be</span> is an open-source project by the INGI department at UCLouvain.') }}
                </p>
                <div class="buttons is-centered">
                    <a href="mailto:covidata@uclouvain.be" class="button is-link is-outlined">{{ _("Contact") }}</a>
                    <a href="/data" class="button is-primary is-outlined">{{ _("Get the data") }}</a>
                    <a href="http://www.github.com/UCL-INGI" class="button is-link is-outlined">{{ _("Open source") }}</a>
                </div>
            </div>
        </footer>
    </body>
</html>